plugins {
    id 'java'
}

allprojects {
    group = 'com.example'
    version = '1.0.0'
    
    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    
    java {
        sourceCompatibility = '21'
        targetCompatibility = '21'
    }
    
    dependencies {
        testImplementation 'org.junit.jupiter:junit-jupiter:5.9.3'
    }
    
    tasks.named('test') {
        useJUnitPlatform()
    }
}
